export const routes = {
  home: "/",
  dashboard: "/dashboard",
  forgotPassword: "/forgot-password",
  confirmEmail: "/confirm-email",
  resetPassword: "/reset-password",
  login: "/login",
  signup: "/signup",
  books: "/books",
  authors: "/authors",
  cart: "/cart",
  genres: "/genres",
  order: "/order",
  orders: "/orders",
};
