export const routes = {
  home: "/",
  dashboard: "/dashboard",
  forgotPassword: "/auth/forgot-password",
  confirmEmail: "/auth/confirm-email",
  resetPassword: "/auth/reset-password",
  login: "/login",
  signup: "/signup",
  books: "/books",
  authors: "/authors",
  cart: "/cart",
  genres: "/genres",
  order: "/order",
  orders: "/orders",
};
